.TH rig-list 1 "May 2023"


.SH NAME
rig list - List all currently running rigs

.SH USAGE
.B rig list

.SH DESCRIPTION
\fBrig list\fR will provide a brief snapshot of all rigs currently running on the
system. This will include the rig's name, start time, type(s) of configured monitor(s)
and action(s) as well as the current status. More detailed information may be gleaned
by using the \fBrig info <name>\fR command.

As of this writing, this command does not accept any options.

.SH MAINTAINER
.nf
Jake Hunsaker <jhunsake@redhat.com>
.fi