.TH rig 1 "January 2019"

.SH NAME
rig \- Monitor a system for events and trigger specific actions
.SH USAGE
.B rig <RESOURCE OR SUBCOMMAND> [OPTIONS] <ACTIONS> [ACTION OPTIONS]

.PP
.SH DESCRIPTION
rig is a tool to assist in troubleshooting seemingly randomly occurring events
or events that occur at times that make active monitoring by a sysadmin difficult.

rig sets-up detached processes, known as 'rigs', that watch a given resource
for a trigger condition, and once that trigger condition is met takes actions
defined by the user.


.SH GLOBAL OPTIONS
The following are options available to all rigs (resources).

.TP
.B \-\-delay DELAY
Specify the number of seconds to wait after a rig is triggered before running
the configured actions. Note that the rig will still trigger and stop all watcher
threads immediately - this delay comes after thread termination but before action
execution in order to avoid a possible race condition where multiple watcher threads
could conceivably trigger during a sufficiently high delay time.

Default 0 seconds, meaning execute actions immediately upon rig trigger condition
being met.

.TP
.B \-\-foreground
Run the rig in the foreground, keeping stdout attached.

.TP
.B \-\-debug
Set logging level to debug instead of the default info level.

.TP
.B \-\-no-archive
Do not create a tar archive of the collected data after a rig has been triggered.

Normally, once all data has been collected, rig will create a gzip'd tar archive under
/var/tmp containing all the files created from the rig's actions - after which,
the temp directory at /var/tmp/rig/<id>/ is deleted.

Using this option skips creating the archive and preserves the temp directory.

.SH SUBCOMMANDS

.TP
.B rig list
Show a list of known existing rigs and their status. Status information is
obtained by querying the socket created for that particular rig.

.TP
.B rig destroy \-i [ID or 'all']
Destroy a deployed rig with id \fBID\fR. If \fBID\fR is 'all', destroy all known
rigs. Note that if another entity kills the pid for the running rig, destroy will
fail as the socket is no longer connected to the (now killed) process. In this case
use the \fB--force\fR option to cleanup the lingering socket.

.TP
.B rig info \-i [ID]
Get detailed information on a rig. This information will include configuration
options, the entire cmdline string given to launch the rig, as well as information
on each action the rig is configured to take and what the expected result from those
action(s) are.

Currently, this data is written to stdout in JSON format.

.SH RESOURCES
These are the system resources that rig can monitor. There may be additional
manpages for specific resources. Where applicable this will be noted below.

Note that 'resources', 'monitors', and referencing 'a rig' as a distinct entity
all refer to the same thing.

When creating a rig, if successful the rig's ID will be printed to console.

.TP
.B logs
Watch a single or multiple log files and/or journald units for a specified
message. When that message is matched to any watched file or journal, the trigger
condition is met and configured actions are initiated.

The following options are available for the \fBlogs\fR rig:
.RS 7
.TP
.B \-m|\-\-message STRING
Define the string that serves as the trigger condition for the rig. This can be
a regex string or an exact message. Be very careful in using the \fB'*'\fR regex
character as this may cause unintended behavior such as the rig immediately
triggering on the first message seen.

Note that a small amount of transformation and testing is done on the provided STRING.
First, '*' characters are converted to the python-style regex match of '.*'. After
which, rig performs a test on if the provided message will regex-match itself, and
if that fails the rig aborts the creation process.

Aside from the conversion noted above, regexes provided in this option must be
python-style and not shell-style.

.TP
.B \-\-logfile FILE
A comma-delimited list of files to watch. Each \fBFILE\fR specified will be
monitored from the current end of the file, so old entries will not set off the
rig's actions.

Default: /var/log/messages
.TP
.B \-\-no-files
Do not monitor any log files.
.TP
.B \-\-journal UNIT
A comma-delimited list of journal units to watch. The journal is watched as a
singular entity, and will be filtered to only read from the provided \fBUNIT(s)\fR.
If no \fBUNIT\fR is specified, the whole system journal will be monitored.

Default: 'system'
.TP
.B \-\-no-journal
Do not monitor the journal.
.TP
.B \-\-count COUNT
The number of times the \fB\-\-message\fR string should be matched before the rig
is triggered. Default 1 - meaning match on the first occurence.

.RE
.TP
.B process
Watch a single process or list of processes for state changes or resource consumption
thresholds. When the process enters the specified state or the specified resource
consumption threshold is met, the trigger condition is met.

The following options are available for the \fBprocess\fR rig:
.RS 7
.TP
.B \-\-proc
A PID or process name of processes to watch. If a process name is specified, then
rig will attempt to convert this to a PID during rig creation. If multiple PIDs
are found, the default behavior is to fail creation and exit. To have rig monitor
all processes found for a process name, use the \fB\-\-all\fR option.
.TP
.B \-\-state STATE
The state that a process needs to be in, in order to trigger the rig. The following
is a list of supported states:

    dead         The process is in a dead (X) state. Should never be seen.
    disk-sleep   The process is in an uninterruptible sleep (D) state.
    running      The process is in a running (R) state.
    sleeping     The process is in an interruptible sleeping (S) state.
    stopped      The process is in a stopped (T) state.
    zombie       The process is a zombie or in Z state.

This can also be set to a "not" value by preceeding one of the above state strings
with a exclaimation mark (!), e.g. '!sleeping' will match any non-sleep (S) state
status for the process(es). Most shells will require you to quote the state string
when using the '!' character.

Note that using '!running' will cause rig to \fBnot\fR trigger against a state
of 'sleeping', as generally speaking 'running' processes spend much of their time
in S state, and it is assumed that triggering against such a process is not desired. 
.TP
.B \-\-rss INTEGER
The amount of rss (resident set size) memory usage to use as a threshold for triggering
the rig. If the process' RSS usage goes above this value, trigger.

The value provided here may be suffixed with K, M, or G to denote the IEC unit.
Rig will convert the provided value and suffix into a value in bytes.
.TP
.B \-\-vms INTEGER
The same as \fB\-\-rss\fR but monitoring Virtual Memory Size instead.
.TP
.B \-\-memperc PERCENT
The percentage of total system memory a process is consuming to use as a threshold
for triggering the rig. If the process' %mem \fBmeets or exceeds\fR this value,
trigger.

\fBPERCENT\fR may be a whole integer or a float. When using a float, the process rig
respects up to \fBtwo (2)\fR decimal points of precision. For example, using
\'\fB\-\-memperc 10.25\fR\' is the same as using \'\fB\-\-memperc 10.25678\fR\'.
.TP
.B \-\-cpuperc PERCENT
The percentage of CPU usage a process is consuming to use as a threshold for
triggering the rig. If the process' %cpu \fBmeets or exceeds\fR this value,
trigger.

\fBPERCENT\fR may be a whole integer or a float. When using a float and monitoring
for CPU usage, rig respects \fBone (1)\fR decimal point of precision due to how CPU
usage is reported.

\fBPERCENT\fR may be above 100 - as CPU usage can exceed 100 when a process is
running on multiple CPUs.

.RE
.TP
.B system

Watch the system's utilization of resources as a whole, e.g. total CPU or memory
usage. When the utilization of a given resource is either exceeded or falls below
the given threshold (determined as appropriate for each resource), the trigger
condition is met.

The following options are available for the \fBsystem\fR rig:
.RS 7
.TP
.B \-\-iowait PERCENT
The amount of %iowait as reported by the kernel to use as a threshold value.

If \fBexceeded\fR, trigger the rig.
.TP
.B \-\-steal PERCENT
The amount of %steal as reported by the kernel to use as a threshold value.

If \fBexceeded\fR, trigger the rig.
.TP
.B \-\-nice PERCENT
The amount of %nice as reported by the kernel to use as a threshold value.

If \fBexceeded\fR, trigger the rig.
.TP
.B \-\-guest PERCENT
The amount of %guest as reported by the kernel to use as a threshold value.

If \fBexceeded\fR, trigger the rig.
.TP
.B \-\-user
The amount of %user as reported by the kernel to use as a threshold value.

If \fBexceeded\fR, trigger the rig.
.TP
.B \-\-available INTEGER
The amount of available memory in MiB as reported by the kernel to use as a threshold value.

If the amount of available memory \fBfalls below\fR this threshold, trigger the rig.
.TP
.B \-\-free INTEGER
The amount of free memory in MiB as reported by the kernel to use as a threshold value.

If the amount of free memory \fBfalls below\fR this threshold, trigger the rig.
.TP
.B \-\-used INTEGER
The amount of used memory in MiB as reported by the kernel to use as a threshold value.

If the amount of used memory \fBexceeds\fR this threshold, trigger the rig.
.TP
.B \-\-slab INTEGER
The amount of slab memory in MiB as reported by the kernel to use as a threshold value.

If the amount of slab memory \fBexceeds\fR this threshold, trigger the rig.
.TP
.B \-\-cpuperc PERCENT
The amount of \fBtotal\fR CPU usage as reported by the kernel as a percentage to
use as a threshold value.

If \fBexceeded\fR, trigger the rig.

This value may be a whole integer or a float. Floats are precise out to one (1)
decimal point.
.TP
.B \-\-memperc PERCENT
The amount of \fBtotal\fR memory usage as reported by the kernel as a percentage
to use as a theshold value.

If \fBexceeded\fR, trigger the rig.

This value may be a whole integer or a float. Floats are precise out to one (1)
decimal point.
.RE

.SH ACTIONS
The following actions are supported responses to triggered rigs. These may be
chained together on a single rig, so deploying multiple rigs with matching trigger
conditions with single, varying actions is unnecessary.

Actions are executed based on a priority weighting system, where lower values
represent a higher priority action, and those actions with lower values are
executed before those with higher values. This is to allow more time-sensitive
actions to be taken before those that may either take a long time to execute or
are otherwise unaffected by allowing other actions to run before them. Action
priority values are set by the actions directly and are currently not able to
be modified by users.
.TP
.B gcore
Collect a coredump of a given process or processes using GDB's \fBgcore\fR utility.

Note that this does _not_ interrupt the running process(es). Cores are saved to
/tmp and will be named either core.$pid or core.$proc_name.$pid depending on if
a PID or process name was provided. This action will be executed first when a rig
is triggered and multiple actions are specified.

The \fBgcore\fR action supports the following options:
.RS 7
.TP
.B \-\-gcore PROCESS
Enables this action and takes either a PID or process name as a value. If a process
name is given, the PID is determined at rig creation. If multiple PIDs are found
for the same process name, the default behavior is to fail rig creation. Use the
\fB\-\-all-pids\fR option to instead use all PIDs discovered for a process name.

This option can be specified multiple times. E.G. \fB\-\-gcore 12345 \-\-gcore
myprocess\fR will generate a coredump for PID 12345 and a process matching the
name 'myprocess'.
.TP
.B \-\-all-pids
Tells this action to collect a coredump for \fBall\fR PIDs found for a provided
process name.
.TP
.RE
.TP
.B kdump
Generate a vmcore by triggering a kernel crash via sysrq.

Note that this action \fBWILL\fR cause node disruption by triggering a kernel panic
to generate the vmcore. This means your system \fBwill reboot\fR when this action
is triggered.

The \fBkdump\fR action does not perform any configuration checks on the system's
kdump installation. It is assumed that kdump has been properly configured and
tested prior to using this action.

The \fBkdump\fR action supports the following options:
.RS 7
.TP
.B \-\-kdump
Enables this action

.TP
.B \-\-sysrq INTEGER
When the rig is deployed, if this option is set, rig will set the system's
\fB/proc/sys/kernel/sysrq\fR to the value provided. See sysrq kernel documentation
for information on what values are supported.
.TP
.RE

.TP
.B sosreport
Run a sosreport after the rig has been triggered. There is some customizability
to the sosreport command that gets run via the \fB\-\-sos-opts\fR option described
below. This action should run after any time-sensitive actions otherwise specified
by the user for a given rig.

The \fBsosreport\fR action supports the following options:
.RS 7
.TP
.B \-\-sosreport
Enables this action
.TP
.B \-\-sos-opts OPTIONS
Specify the commandline options to use when running sosreport. Note that rig
does not do any verification of the \fBOPTIONS\fR being passed to sosreport.
.TP
.RE
.TP
.B tcpdump
Start collecting a tcpdump when the rig is initialized, and stop the collection
when the rig triggers. This action will be triggered before most other actions,
but after the gcore action.

Note there will be a slight delay in configuring any rig that uses the tcpdump
action as rig must verify that the tcpdump process started successfully during
the initialization process.

The \fBtcpdump\fR action supports the following options:
.RS 7
.TP
.B \-\-tcpdump
Enables this action
.TP
.B \-\-iface INTERFACE
Starts the tcpdump to monitor the provided INTERFACE. In almost all situations
this should likely be set to a specific interface on the system, however the
value of 'any' is accepted by the tcpdump command in order to listen on all
interfaces. Be wary of using this however as use of 'any' means will make it
impossible to determine which interface a particular packet came in on in the
resulting packet capture.

Default: eth0
.TP
.B \-\-filter FILTER
Provide a filter to use with tcpdump in order to reduce the amount of traffic
recorded in the packet capture. This value is passed directly to the tcpdump
utility, and thus can be any valid filter accepted by tcpdump.

\fBFor most shells you must quote the filter string for rig to pass it correctly.\fR
.TP
.B \-\-size SIZE
Limit the size of the packet capture file(s) to SIZE in MB.

Default: 10
.TP
.B \-\-captures CAPTURES
Specify the number of packet capture files to keep. If more than one (1), then
tcpdump will rotate the packet capture file when it reaches the \fB\-\-size\fR
value and keep CAPTURES number of files.

E.G. Using a CAPTURES of 2 and a SIZE of 5, then when the rig terminates you will
have up to 2 5MB packet captures.

Default: 1 (packet capture file is replaced upon reaching SIZE limit).
.TP
.RE
.TP
.B noop

Does nothing - this action runs a no-op. This is ideally used for when you need
to test a rig's configuration to make sure a rig's trigger condition is set
properly - e.g. a regex string for the logs' rig message option.

The \fBnoop\fR action supports the following options:
.RS 7
.TP
.B \-\-noop
Enables this action
.RE
.SH MAINTAINER
.nf
Jake Hunsaker <jhunsake@redhat.com>
.fi
