.TH rig 1 "May 2023"

.SH NAME
rig \- Monitor a system for events and trigger specific actions
.SH USAGE
.B rig <COMMAND> [OPTIONS]

.PP
.SH DESCRIPTION
rig is a tool to assist in troubleshooting seemingly randomly occurring events
or events that occur at times that make active monitoring by a sysadmin difficult.

rig configures detached processes, known as 'rigs', that monitor a specified resource
for a given condition, and then take specified actions once that condition is met.
These monitors and actions are defined in yaml-formatted 'rigfiles'.

.SH COMMANDS

The following commands are available to rig; users should see \fBman rig-<command>\fR
for more information:

    \fBcreate\fR            Start a new rig based on a provided rigfile
    \fBdestroy\fR           Destroy a rig without trigger its actions
    \fBtrigger\fR           Manually trigger a rig's action right now
    \fBinfo\fR              Get detailed information on a rig
    \fBlist\fR              List all currently running rigs
    \fBmonitors\fR          Show information on supported monitors
    \fBactions\fR           Show information on support actions

.SH MONITORS

Rigs are configured to check for specific conditions via the use of "monitors". These
monitors are specific to a type of condition that users may be interested in leveraging to
facilitate data collection via rig actions.

See \fBrig list-monitors\fR for detailed information on the available monitors.

.SH ACTIONS

When a particular rig has at least one monitor reach it's configured condition, the rig
is "triggered". At this point, all other monitors are stopped, the rig's configured action(s)
are executed, and then the results of those action(s) are saved into a tarball alongside a log file
for the specific rig which generated was triggered.

Actions generally center around data collection at the time a monitor's condition is met, however
some such as the 'tcpdump' action may collect data over the life of the rig.

See \fBrig list-actions\fR for more detailed information on the available actions.

.SH MAINTAINER
.nf
Jake Hunsaker <jhunsake@redhat.com>
.fi
